POST http://localhost:4011/api/users
Content-Type: application/json

{
  "firstName": "Le",
  "lastName": "Rucci",
  "email": "rucci@gmail.com",
  "password": "rucci123",
  "phoneNumber": "08122345"
}